apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-jaeger-client
  namespace: observability
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-jaeger-client
  template:
    metadata:
      labels:
        app: flask-jaeger-client
    spec:
      containers:
      - name: flask-jaeger-client
        image: rootpromptnext/flask-jaeger-client-client:v1
        ports:
        - containerPort: 5000
        env:
        - name: JAEGER_AGENT_HOST
          value: "jaeger.observability.svc.cluster.local"
        - name: JAEGER_AGENT_PORT
          value: "6831"
---
apiVersion: v1
kind: Service
metadata:
  name: flask-jaeger-client
  namespace: observability
spec:
  type: NodePort
  selector:
    app: flask-jaeger-client
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30500
